import { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import type { TipoPaciente } from "../../types/tipos/Pacientes/tipoPaciente";

export default function Menu(){
  
  const [paciente, setPaciente] = useState<TipoPaciente>();

  useEffect(() =>{
      const dadosSalvos = sessionStorage.getItem("paciente");
      if (dadosSalvos) {
          setPaciente(JSON.parse(dadosSalvos));
      }
  }, []);

  const location = useLocation(); /*Hook que possui um método que verificar se a localização atual página, ex:location.pathname === '/' verifica se a localização da página é a '/', no caso a página HOME*/

    return(
        <div>
          {paciente? ( 
          <div className="flex flex-col m-5 mt-[8rem] justify-center items-center gap-5 p-4 sm:mt-[13.3rem] md:mt-[9rem] lg:mt-[6rem] lg:fixed lg:bg-[var(--btn-color-menu)] lg:flex-wrap lg:h-[10vh] lg:p-0 lg:m-0  xl:fixed xl:mt-[7rem] 2xl:mt-[7.4rem] 2xl:fixed 2xl:bg-[var(--btn-color-menu)] lg:w-full xl:w-full 2xl:w-ful"><Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/">Home</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/FAQ' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`}  to="/FAQ">Dúvidas Frequentes</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/contato' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/contato">Contato</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/integrantes' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/integrantes">Integrantes</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/agendamento' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/agendamento">Agendamento</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/guia' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/guia">Guia</Link> 
          </div>): 
          (
          <div className="flex flex-col m-5 mt-[8rem] justify-center items-center gap-5 p-4 sm:mt-[13.3rem] md:mt-[9rem] lg:mt-[6rem] lg:fixed lg:bg-[var(--btn-color-menu)] lg:flex-wrap lg:h-[10vh] lg:p-0 lg:m-0  xl:fixed xl:mt-[7rem] 2xl:mt-[7.4rem] 2xl:fixed 2xl:bg-[var(--btn-color-menu)] lg:w-full xl:w-full 2xl:w-ful">
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/">Home</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/FAQ' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`}  to="/FAQ">Dúvidas Frequentes</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/contato' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/contato">Contato</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/integrantes' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/integrantes">Integrantes</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/agendamento' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/agendamento">Agendamento</Link>
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/guia' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/guia">Guia</Link> 
            <Link className={`flex items-center justify-center bg-[var(--btn-color-menu)] w-[var(--btn-size-X-menu)] h-[var(--btn-size-Y-menu)] text-[1.2rem] text-center text-white font-bold rounded-2xl shadow-2xl shadow-lg sm:text-[1.5rem] lg:w-[12.7vw] lg:h-[10vh] lg:shadow-none lg:text-[1rem] xl:h-[10vh]  xl:w-[13.1vw] 2xl:h-[7.6vh] 2xl:w-[13.5vw] hover:bg-[var(--color-font-rodape)] lg:h-[10vh] lg:rounded-none lg:w-[12.7vw] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] transition-all duration-300 ${location.pathname === '/login-or-create-account' ? 'shadow-lg bg-[var(--btn-color-menu-atual)] lg:rounded-none lg:w-[12.7vw] lg:h-[10vh] xl:h-[10vh] xl:w-[13.1vw] 2xl:h-[10vh] 2xl:w-[13.5vw] hover:bg-[var(--btn-color-menu-atual)]' : ''}`} to="/login-or-create-account">Entrar</Link> 
          </div>)}
        </div>
    );
}